[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "urllib3>=2.5.0",
]
